name: Cypress

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Start client
      run: npm run dev
    - name: Run Cypress
      run: npm run test:cy
